app/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults

admin.site.index_title = admin.site.name = admin.site.site_header = admin.site.site_title = "BVA Search Admin"

urlpatterns = [
    path("", include("decisions.urls"), name="decisions"),
    path("", include("index.urls"), name="index"),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
    urlpatterns.extend(
        [
            path("__debug__/", include("debug_toolbar.urls")),
            path(
                "400/",
                defaults.bad_request,
                kwargs={"exception": Exception("Bad Request")},
            ),
            path(
                "403/",
                defaults.permission_denied,
                kwargs={"exception": Exception("Permission Denied")},
            ),
            path(
                "404/",
                defaults.page_not_found,
                kwargs={"exception": Exception("Not Found")},
            ),
            path("500/", defaults.server_error),
        ],
    )

app/decisions/urls.py
from django.urls import path

from decisions import views

app_name = "decisions"

urlpatterns = [
    path("", views.SearchView.as_view(), name="search"),
    path("results/", views.ResultsView.as_view(), name="results"),
    path("decision/<str:pk>/", views.DecisionView.as_view(), name="decision"),
]

app/index/urls.py
from django.urls import path

from index import views

app_name = "index"

urlpatterns = [
    path("about/", views.AboutView.as_view(), name="about"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path("privacy/", views.PrivacyView.as_view(), name="privacy"),
    path("terms/", views.TermsView.as_view(), name="terms"),
]

app/templates/components/footer.html
<footer class="container-fluid d-flex flex-wrap justify-content-between align-items-center py-3 my-4">
  <div class="col-md-4">
    <p class="mx-4 mb-0 text-body-secondary">© BVA Search</p>
  </div>
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <ul class="nav justify-content-end mx-4">
      <li class="nav-item"><a href="https://www.va.gov/" class="nav-link px-2 text-body-secondary">VA.gov</a></li>
      <li class="nav-item"><a href="https://www.ecfr.gov/current/title-38/chapter-I/part-4/" class="nav-link px-2 text-body-secondary">CFR 38</a></li>
      <li class="nav-item"><a href="https://www.veteransbenefitskb.com/" class="nav-link px-2 text-body-secondary">VBKB</a></li>
      <li class="nav-item"><a href="{% url 'index:about' %}" class="nav-link px-2 text-body-secondary">About</a></li>
      <li class="nav-item"><a href="{% url 'index:contact' %}" class="nav-link px-2 text-body-secondary">Contact</a></li>
      <li class="nav-item"><a href="{% url 'index:privacy' %}" class="nav-link px-2 text-body-secondary">Privacy</a></li>
      <li class="nav-item"><a href="{% url 'index:terms' %}" class="nav-link px-2 text-body-secondary">Terms</a></li>
    </ul>
  </div>
</footer>

app/templates/components/header.html
<header class="container-fluid d-flex flex-wrap justify-content-center py-3 mb-4">
  <a href="{% url 'decisions:search' %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
    <span class="fs-3 ms-3">BVA Search</span>
  </a>
  {% include "decisions/components/search_form.html" %}
  <div class="text-end ms-2">
    <button type="button" class="btn btn-outline-secondary me-2" id="themeToggle">
      <i class="bi bi-moon" id="themeIcon"></i>
    </button>
  </div>
</header>