app/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults

admin.site.index_title = admin.site.name = admin.site.site_header = admin.site.site_title = "BVA Search Admin"

urlpatterns = [
    path("", include("decisions.urls"), name="decisions"),
    path("", include("index.urls"), name="index"),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
    urlpatterns.extend(
        [
            path("__debug__/", include("debug_toolbar.urls")),
            path(
                "400/",
                defaults.bad_request,
                kwargs={"exception": Exception("Bad Request")},
            ),
            path(
                "403/",
                defaults.permission_denied,
                kwargs={"exception": Exception("Permission Denied")},
            ),
            path(
                "404/",
                defaults.page_not_found,
                kwargs={"exception": Exception("Not Found")},
            ),
            path("500/", defaults.server_error),
        ],
    )

app/index/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

app/index/templates/index/about.html
{% extends "index/base.html" %}

{% block title %}About{% endblock %}

{% block content %}
  <div class="container bg-body text-body">
    <h1>About</h1>
  </div>
{% endblock %}

app/index/templates/index/base.html
{% extends "base.html" %}

app/index/templates/index/contact.html
{% extends "index/base.html" %}

{% block title %}Contact{% endblock %}

{% block content %}
  <div class="container bg-body text-body">
    <h1>Contact</h1>
    <form method="post">
      {% csrf_token %}
      <label for="id_name">Name:</label>
      <input type="text" name="name" maxlength="100" required id="id_name" class="form-control">
      <label for="id_email">Email:</label>
      <input type="email" name="email" maxlength="254" required id="id_email" class="form-control">
      <label for="id_message">Message:</label>
      <textarea name="message" cols="40" rows="10" required id="id_message" class="form-control"></textarea>
      <input type="submit" value="Submit" class="btn btn-primary">
      <input type="reset" value="Reset" class="btn btn-secondary">
    </form>
  </div>
{% endblock %}

app/index/templates/index/privacy.html
{% extends "index/base.html" %}

{% block title %}Privacy{% endblock %}

{% block content %}
  <div class="container bg-body text-body">
    <h1>Privacy</h1>
  </div>
{% endblock %}

app/index/templates/index/terms.html
{% extends "index/base.html" %}

{% block title %}Terms{% endblock %}

{% block content %}
  <div class="container bg-body text-body">
    <h1>Terms</h1>
  </div>
{% endblock %}