app/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults

admin.site.index_title = admin.site.name = admin.site.site_header = admin.site.site_title = "BVA Search Admin"

urlpatterns = [
    path("", include("decisions.urls"), name="decisions"),
    path("", include("index.urls"), name="index"),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
    urlpatterns.extend(
        [
            path("__debug__/", include("debug_toolbar.urls")),
            path(
                "400/",
                defaults.bad_request,
                kwargs={"exception": Exception("Bad Request")},
            ),
            path(
                "403/",
                defaults.permission_denied,
                kwargs={"exception": Exception("Permission Denied")},
            ),
            path(
                "404/",
                defaults.page_not_found,
                kwargs={"exception": Exception("Not Found")},
            ),
            path("500/", defaults.server_error),
        ],
    )

app/decisions/management/commands/urls.py
import bs4
import requests
from django.core.management.base import BaseCommand

from decisions.models import Decision
from tasks.models import Task

TASK_NAME = "urls"


class Command(BaseCommand):
    help = "Fetch urls from BVA sitemaps"

    def handle(self, *args, **options):
        created_objects = 0
        main_sitemap_soup = request_sitemap(url="https://www.va.gov/sitemap_bva.xml")

        if not main_sitemap_soup:
            self.record_error(f"Error requesting main sitemap: https://www.va.gov/sitemap_bva.xml")
            return

        sitemap_list = extract_annual_sitemaps(soup=main_sitemap_soup)
        last_run = get_last_run()
        filtered_sitemap_list = filter_list(elements=sitemap_list, last_run=last_run)

        for sitemap_dict in filtered_sitemap_list:
            self.stdout.write(f"Requesting {sitemap_dict['loc']}")
            annual_sitemap_soup = request_sitemap(url=sitemap_dict["loc"])
            if not annual_sitemap_soup:
                self.record_error(f"Error requesting annual sitemap: {sitemap_dict['loc']}")
                continue
            url_list = extract_sitemap_urls(soup=annual_sitemap_soup)
            filtered_url_list = filter_list(elements=url_list, last_run=last_run)
            decisions = create_decisions(urls=filtered_url_list)
            objects = Decision.objects.bulk_create(decisions, ignore_conflicts=True)
            created_objects += len(objects)

        self.record_success(f"{created_objects} decisions created")

    def record_success(self, msg: str):
        self.stdout.write(self.style.SUCCESS(msg))
        Task.objects.create(
            name=TASK_NAME,
            status=True,
            description=msg,
        )

    def record_error(self, msg: str):
        self.stdout.write(self.style.ERROR(msg))
        Task.objects.create(
            name=TASK_NAME,
            status=False,
            description=msg,
        )


def request_sitemap(url: str) -> bs4.BeautifulSoup | None:
    response = requests.get(url)
    try:
        response.raise_for_status()
    except requests.exceptions.HTTPError:
        return None
    return bs4.BeautifulSoup(response.content, "lxml-xml")


def extract_annual_sitemaps(soup: bs4.BeautifulSoup) -> list[dict[str, str]]:
    output = []
    sitemap_index = soup.find("sitemapindex")
    sitemap_elements = sitemap_index.find_all("sitemap")
    for sitemap_element in sitemap_elements:
        loc = sitemap_element.find("loc").text
        lastmod = sitemap_element.find("lastmod").text
        output.append(
            {
                "loc": loc,
                "lastmod": lastmod,
            }
        )
    return output


def get_last_run() -> str:
    task = Task.objects.filter(name=TASK_NAME, status=True).order_by("-datetime").first()
    if not task:
        return "1970-01-01"
    else:
        return task.datetime.date().strftime("%Y-%m-%d")


def filter_list(elements: list[dict[str, str]], last_run: str) -> list[dict[str, str]]:
    output = []
    for element in elements:
        if element["lastmod"] > last_run:
            output.append(element)
    return output


def extract_sitemap_urls(soup: bs4.BeautifulSoup) -> list[dict[str, str]]:
    output = []
    url_set = soup.find("urlset")
    url_elements = url_set.find_all("url")
    for url_element in url_elements:
        loc = url_element.find("loc").text
        lastmod = url_element.find("lastmod").text
        output.append(
            {
                "loc": loc,
                "lastmod": lastmod,
            }
        )
    return output


def create_decisions(urls: list[dict[str, str]]) -> list[Decision]:
    decisions = []
    for url in urls:
        # https://www.va.gov/vetapp25/Files5/A25048321.txt -> A25048321
        pk = url["loc"].split("/")[-1].split(".")[0]
        decision = Decision(
            id=pk,
            url=url["loc"],
            lastmod=url["lastmod"],
        )
        decisions.append(decision)
    return decisions

app/decisions/urls.py
from django.urls import path

from decisions import views

app_name = "decisions"

urlpatterns = [
    path("", views.SearchView.as_view(), name="search"),
    path("results/", views.ResultsView.as_view(), name="results"),
    path("decision/<str:pk>/", views.DecisionView.as_view(), name="decision"),
]

app/decisions/models.py
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVectorField
from django.db import models


class Decision(models.Model):
    id = models.CharField(max_length=32, primary_key=True)
    url = models.URLField(unique=True)
    lastmod = models.DateField()
    text = models.TextField(null=True, blank=True)
    search_vector = SearchVectorField(null=True, blank=True)
    date = models.DateField(null=True, blank=True)

    class Meta:
        indexes = [
            GinIndex(fields=["search_vector"]),
        ]


class Query(models.Model):
    string = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Queries"
        ordering = ["-created"]

app/decisions/views.py
import datetime
import urllib.parse

from django.contrib.postgres.search import SearchHeadline, SearchQuery, SearchRank
from django.db.models import F
from django.views.generic import DetailView, ListView, TemplateView

from decisions.models import Decision, Query
from tasks.models import Task


class SearchView(TemplateView):
    template_name = "decisions/search.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["decision_count"] = Decision.objects.all().count()
        latest_datetime = Task.objects.filter(name="urls").order_by("-datetime").first()
        context["latest_date"] = latest_datetime.datetime.date().strftime("%x")
        return context


class ResultsView(ListView):
    model = Decision
    template_name = "decisions/results.html"
    paginate_by = 100

    def get(self, request, *args, **kwargs):
        q = self.request.GET.get("q", "").strip()
        if q:
            Query.objects.create(string=q)
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        q = self.request.GET.get("q", "").strip()
        if not q:
            return Decision.objects.none()

        today = datetime.date.today()
        start_date = datetime.date(year=today.year - 1, month=1, day=1)
        query = SearchQuery(q, search_type="websearch", config="english")
        query_set = Decision.objects.filter(search_vector=query)
        query_set = (
            query_set.annotate(
                rank=SearchRank(F("search_vector"), query),
                headline=SearchHeadline(
                    expression=F("text"),
                    query=query,
                    start_sel="<mark>",
                    stop_sel="</mark>",
                ),
            )
            .filter(
                date__range=(start_date, today),
            )
            .order_by("-rank")
            .values("pk", "headline", "date", "url")
        )
        return query_set

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        q = self.request.GET.get("q", "").strip()
        context["query"] = q
        context["query_url"] = urllib.parse.quote_plus(q)
        return context


class DecisionView(DetailView):
    model = Decision
    template_name = "decisions/decision.html"

app/decisions/templates/decisions/decision.html
{% extends "decisions/base.html" %}

{% block title %}{{ decision.pk }}{% endblock %}

{% block extra_head %}
  <style>
    body {
      font-size: 1.1rem;
      line-height: 1.6;
    }
  </style>
{% endblock %}

{% block content %}
  <div class="container my-3">
    <div class="row my-3">
      <div class="col-10 mx-auto">
        {{ decision.text|linebreaks }}
      </div>
    </div>
  </div>
{% endblock %}

app/decisions/templates/decisions/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
      <a href="?{% if query_url %}q={{ query_url }}&{% endif %}page=1">&laquo; first</a>
      <a href="?{% if query_url %}q={{ query_url }}&{% endif %}page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
      <a href="?{% if query_url %}q={{ query_url }}&{% endif %}page={{ page_obj.next_page_number }}">next</a>
      <a href="?{% if query_url %}q={{ query_url }}&{% endif %}page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>

app/decisions/templates/decisions/results.html
{% extends "decisions/base.html" %}

{% block title %}Results{% endblock %}

{% block content %}
  <div class="container">
    <div class="row my-3">
      <div class="col-10 mx-auto">
        {% if decision_list %}
          {% for decision in decision_list %}
            <div class="card my-3 border-0">
              <div class="card-body">
                <h5 class="card-title">
                  <span class="me-2">{{ forloop.counter }}.</span>
                  <a href="{% url 'decisions:decision' pk=decision.pk %}" class="text-decoration-none">{{ decision.pk }}</a>
                </h5>
                <p class="card-text my-2">{{ decision.headline|safe }}</p>
                <p class="card-text text-small">
                  <small class="text-body-secondary me-3">
                    {{ decision.date }}
                  </small>
                  <small class="text-body-secondary">
                    <a href="{{ decision.url }}" class="text-decoration-none">Source</a>
                  </small>
                </p>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <div>
            <p>No results found.</p>
          </div>
        {% endif %}
      </div>
    </div>
    <div class="row my-5">
      <div class="col-10 mx-auto d-flex justify-content-center">
        {% include "decisions/pagination.html" %}
      </div>
    </div>
  </div>
{% endblock %}

app/decisions/templates/decisions/search.html
{% extends "decisions/base.html" %}
{% load humanize %}

{% block title %}Search{% endblock %}

{% block content %}
  <div class="container bg-body text-body">
    <div class="row my-5">
      <div class="p-5 text-center rounded-3">
        <h1 class="text-body-emphasis">BVA Search</h1>
        <p class="lead">
          Search Board of Veterans' Appeals Decisions
        </p>
      </div>
    </div>
    <div class="row my-5">
      <div class="col-8 mx-auto">
        {% include "decisions/components/search_form.html" %}
      </div>
    </div>
    <div class="row my-5">
      <div class="col-8 mx-auto">
        <p class="text-center">{{ decision_count|intcomma }} Decisions as of {{ latest_date }}</p>
      </div>
    </div>
  </div>
{% endblock %}